### PR TITLE
Support CharSequence as DBusType

### PR DESCRIPTION
**Pull request by Xerus2000**
I can't test this with my knowledge, but I hope it doesn't affect anything else. Background is that I want to implement certain Properties via enums, which can implement CharSequence but can't extend String (obviously).

And of course some further cleanups to clarify naming.

### CODE REVIEW

**Comment by hypfvieh** [comment]
Replacing String.class with CharSequence.class is not enough.
We need to have both, String and CharSequence as the method is just comparing type or class name and does not do something like 'instanceof' or 'isAssignableFrom'. 

So without String.class added as another 'else if' the unit tests will instantly fail and tell you that String.class is not an exportable type.

I fixed that issue in your pull request. I will also add the CharSequence change to dbus-3.0.

**Comment by Xerus2000** [comment]
oh right, it should be `instanceof CharSequence`, because otherwise subclasses are going to be ignored and it's useless ^^

**Comment by hypfvieh** [comment]
yep... I'll take a look at that piece of code (was on my todo list for 3.0 anyway) and will backport it to 2.7.5 if I've a suitable solution

**Comment by hypfvieh** [comment]
I just updated the Marshalling class to hopefully support CharSequence.

**Pull request merged**
